import { Platform, StyleSheet } from "react-native";
import { MAX_WIDTH } from "./dashboardTheme";

export const styles = StyleSheet.create({
screen: {
flex: 1,
backgroundColor: "#111827",
alignItems: "center",
justifyContent: "center",
},
screenTv: {
// Escape the normal Expo/React Native web wrapper and force the dashboard
// to fill the actual browser/cast viewport in TV mode.
position: "fixed" as any,
top: 0,
right: 0,
bottom: 0,
left: 0,
width: "100vw" as any,
height: "100vh" as any,
alignItems: "stretch",
justifyContent: "flex-start",
backgroundColor: "#F8FAFC",
zIndex: 9999,
},
appFrame: {
width: "100%",
maxWidth: MAX_WIDTH,
height: Platform.OS === "web" ? 780 : "100%",
backgroundColor: "#F8FAFC",
borderRadius: Platform.OS === "web" ? 22 : 0,
overflow: "hidden",
},
appFrameTv: {
// True TV mode: fill the full 16:9 browser viewport instead of showing
// the laptop-sized dashboard as a floating card inside the screen.
position: "fixed" as any,
top: 0,
right: 0,
bottom: 0,
left: 0,
width: "100vw" as any,
maxWidth: "none" as any,
height: "100vh" as any,
borderRadius: 0,
shadowOpacity: 0,
},
topBar: {
height: 112,
paddingHorizontal: 26,
paddingVertical: 14,
backgroundColor: "#F54FA5",
flexDirection: "row",
justifyContent: "space-between",
alignItems: "center",
},
topBarTv: {
height: 104,
paddingHorizontal: 42,
paddingVertical: 12,
},
topLeftBlock: {
flex: 1,
paddingRight: 18,
},
locationText: {
color: "#FFFFFF",
fontSize: 25,
fontWeight: "900",
},
programText: {
marginTop: 4,
color: "#FFE4F4",
fontSize: 15,
fontWeight: "800",
},
dateText: {
marginTop: 3,
color: "#FFE4F4",
fontSize: 14,
fontWeight: "800",
},
cycleText: {
marginTop: 3,
color: "#FFE4F4",
fontSize: 12,
fontWeight: "700",
},
voiceToggle: {
marginTop: 7,
paddingHorizontal: 11,
paddingVertical: 6,
borderRadius: 999,
borderWidth: 1,
borderColor: "rgba(255,255,255,0.72)",
backgroundColor: "rgba(255,255,255,0.14)",
},
voiceToggleEnabled: {
backgroundColor: "rgba(255,255,255,0.28)",
},
voiceToggleText: {
color: "#FFFFFF",
fontSize: 11,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.5,
},
clockBlock: {
alignItems: "flex-end",
},
clockText: {
color: "#FFFFFF",
fontSize: 28,
fontWeight: "900",
},
currentPanelBar: {
height: 48,
backgroundColor: "#FFFFFF",
borderBottomWidth: 1,
borderBottomColor: "#E5E7EB",
paddingHorizontal: 24,
flexDirection: "row",
alignItems: "center",
justifyContent: "space-between",
},
currentPanelBarTv: {
height: 42,
paddingHorizontal: 28,
},
currentPanelPill: {
paddingHorizontal: 18,
paddingVertical: 8,
borderRadius: 999,
backgroundColor: "#111827",
},
currentPanelLabel: {
fontSize: 13,
fontWeight: "800",
color: "#FFFFFF",
},
currentPanelValue: {
fontWeight: "900",
color: "#FFFFFF",
},
currentPanelCount: {
fontSize: 12,
fontWeight: "800",
color: "#6B7280",
},
contentArea: {
flex: 1,
padding: 16,
},
contentAreaTv: {
padding: 14,
},
panel: {
flex: 1,
backgroundColor: "#FFFFFF",
borderRadius: 18,
padding: 14,
shadowColor: "#000",
shadowOpacity: 0.04,
shadowRadius: 8,
shadowOffset: { width: 0, height: 3 },
},
panelHeaderRow: {
flexDirection: "row",
justifyContent: "space-between",
alignItems: "flex-start",
gap: 14,
marginBottom: 10,
},
panelEyebrow: {
color: "#6B7280",
fontSize: 13,
fontWeight: "800",
textTransform: "uppercase",
letterSpacing: 0.7,
},
panelTitle: {
marginTop: 2,
fontSize: 28,
fontWeight: "900",
color: "#111827",
},
badge: {
flexDirection: "row",
alignItems: "center",
gap: 8,
backgroundColor: "#DCFCE7",
borderColor: "#DDD6FE",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 8,
},
badgeText: {
color: "#059669",
fontWeight: "800",
fontSize: 12,
},
legendRow: {
flexDirection: "row",
alignItems: "center",
gap: 8,
flexWrap: "wrap",
justifyContent: "flex-end",
},
legendPill: {
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 12,
paddingVertical: 7,
},
legendBlue: {
backgroundColor: "#FFFFFF",
borderColor: "#D1D5DB",
},
legendOrange: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
legendPurple: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
legendText: {
color: "#4B5563",
fontSize: 12,
fontWeight: "900",
},
legendTextOrange: {
color: "#C2410C",
fontSize: 12,
fontWeight: "900",
},
legendTextPurple: {
color: "#6D28D9",
fontSize: 12,
fontWeight: "900",
},
assignmentGrid: {
flexDirection: "row",
flexWrap: "wrap",
gap: 10,
paddingBottom: 8,
},
assignmentCard: {
width: "31.9%",
minHeight: 78,
borderRadius: 18,
borderWidth: 2,
paddingHorizontal: 10,
paddingVertical: 8,
justifyContent: "flex-start",
},
assignmentCardOnsite: {
backgroundColor: "#FFFFFF",
borderColor: "#E5E7EB",
},
assignmentCardOuting1: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
assignmentCardOuting2: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
assignmentStaffPill: {
alignSelf: "flex-start",
borderRadius: 999,
borderWidth: 1.5,
paddingHorizontal: 10,
paddingVertical: 5,
maxWidth: "100%",
},
assignmentStaffPillOnsite: {
backgroundColor: "#F54FA5",
borderColor: "#F54FA5",
},
assignmentStaffPillOuting1: {
backgroundColor: "#FFEDD5",
borderColor: "#FB923C",
},
assignmentStaffPillOuting2: {
backgroundColor: "#EDE9FE",
borderColor: "#8B5CF6",
},
assignmentStaffName: {
fontSize: 18,
lineHeight: 22,
fontWeight: "900",
},
assignmentStaffNameOnsite: {
color: "#FFFFFF",
},
assignmentStaffNameOuting1: {
color: "#C2410C",
},
assignmentStaffNameOuting2: {
color: "#6D28D9",
},
assignmentParticipantList: {
marginTop: 7,
flexDirection: "row",
flexWrap: "wrap",
gap: 6,
},
assignmentParticipantChip: {
borderRadius: 999,
borderWidth: 1.5,
paddingHorizontal: 9,
paddingVertical: 4,
maxWidth: "100%",
},
assignmentParticipantChipOnsite: {
backgroundColor: "#6F82F6",
borderColor: "#5868E8",
},
assignmentParticipantChipOuting1: {
backgroundColor: "#FFEDD5",
borderColor: "#FB923C",
},
assignmentParticipantChipOuting2: {
backgroundColor: "#EDE9FE",
borderColor: "#8B5CF6",
},
assignmentParticipantName: {
fontSize: 13,
lineHeight: 16,
fontWeight: "900",
},
assignmentParticipantNameOnsite: {
color: "#FFFFFF",
},
assignmentParticipantNameOuting1: {
color: "#C2410C",
},
assignmentParticipantNameOuting2: {
color: "#6D28D9",
},
floatingTable: {
flex: 1,
borderWidth: 1,
borderColor: "#E5E7EB",
borderRadius: 16,
overflow: "hidden",
},
floatRow: {
flexDirection: "row",
minHeight: 42,
borderBottomWidth: 1,
borderBottomColor: "#E5E7EB",
},
floatHeaderRow: {
minHeight: 38,
backgroundColor: "#EEF2FF",
},
rowEven: {
backgroundColor: "#FFFFFF",
},
rowOdd: {
backgroundColor: "#F9FAFB",
},
currentFloatRow: {
backgroundColor: "#DCFCE7",
borderLeftWidth: 8,
borderLeftColor: "#10B981",
},
floatCell: {
flex: 1,
paddingHorizontal: 10,
paddingVertical: 10,
},
floatHeaderText: {
fontSize: 13,
color: "#111827",
fontWeight: "900",
},
floatTimeCell: {
flex: 1.05,
},
floatCellBox: {
flex: 1,
justifyContent: "center",
paddingHorizontal: 10,
borderRightWidth: 1,
borderRightColor: "#E5E7EB",
},
floatTimeCellBox: {
flex: 1.05,
},
floatTimeText: {
fontSize: 14,
fontWeight: "800",
color: "#111827",
},
floatNameText: {
fontSize: 16,
fontWeight: "800",
color: "#111827",
},
floatEmptyText: {
fontSize: 16,
fontWeight: "800",
color: "#9CA3AF",
},
fsoText: {
color: "#F54FA5",
fontWeight: "900",
},
currentText: {
color: "#065F46",
},
nowLabel: {
marginTop: 2,
fontSize: 10,
color: "#059669",
fontWeight: "900",
},
outingGrid: {
flex: 1,
flexDirection: "row",
gap: 16,
marginTop: 12,
},
outingCard: {
flex: 1,
borderRadius: 22,
borderWidth: 2,
padding: 20,
},
outingCardOrange: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
outingCardPurple: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
outingTitleRow: {
flexDirection: "row",
alignItems: "center",
gap: 14,
marginBottom: 16,
},
outingIcon: {
width: 52,
height: 52,
borderRadius: 999,
alignItems: "center",
justifyContent: "center",
},
outingIconOrange: {
backgroundColor: "#F97316",
},
outingIconPurple: {
backgroundColor: "#7C3AED",
},
outingLabel: {
fontSize: 13,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.7,
},
orangeText: {
color: "#C2410C",
},
purpleText: {
color: "#6D28D9",
},
outingName: {
fontSize: 28,
fontWeight: "900",
color: "#111827",
},
outingTime: {
fontSize: 16,
color: "#4B5563",
fontWeight: "800",
},
outingSection: {
marginTop: 14,
},
outingSectionTitle: {
fontSize: 13,
fontWeight: "900",
color: "#374151",
textTransform: "uppercase",
letterSpacing: 0.5,
marginBottom: 4,
},
outingSectionText: {
fontSize: 18,
lineHeight: 25,
fontWeight: "700",
color: "#111827",
},
eventsGrid: {
flex: 1,
flexDirection: "row",
gap: 14,
marginTop: 8,
},
eventsColumn: {
flex: 1,
borderRadius: 18,
borderWidth: 1,
borderColor: "#F3E8FF",
backgroundColor: "#FFF7FD",
padding: 12,
},
eventsSectionTitle: {
fontSize: 16,
fontWeight: "900",
color: "#111827",
marginBottom: 10,
},
eventsList: {
gap: 11,
paddingBottom: 4,
},
eventCard: {
flexDirection: "row",
alignItems: "flex-start",
gap: 14,
borderRadius: 24,
borderWidth: 1.5,
padding: 15,
},
eventIconCircle: {
width: 58,
height: 58,
borderRadius: 29,
alignItems: "center",
justifyContent: "center",
},
eventCardBody: {
flex: 1,
},
eventCardHeader: {
flexDirection: "row",
alignItems: "flex-start",
gap: 10,
},
eventStatusLabel: {
fontSize: 12,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.8,
},
eventSubtitle: {
marginTop: 4,
fontSize: 14,
lineHeight: 18,
fontWeight: "800",
},
eventTitle: {
marginTop: 3,
fontSize: 20,
lineHeight: 24,
fontWeight: "900",
color: "#111827",
},
eventCategoryPill: {
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 10,
paddingVertical: 5,
},
eventCategoryText: {
fontSize: 11,
fontWeight: "900",
},
eventTypeText: {
marginTop: 8,
fontSize: 14,
fontWeight: "900",
color: "#4B5563",
},
eventDetailText: {
marginTop: 4,
fontSize: 14,
fontWeight: "700",
color: "#374151",
},
eventNoteBox: {
marginTop: 9,
borderRadius: 14,
paddingHorizontal: 10,
paddingVertical: 8,
},
eventNoteText: {
fontSize: 14,
lineHeight: 19,
fontWeight: "800",
},
eventSummaryBadge: {
flexDirection: "row",
alignItems: "center",
gap: 8,
backgroundColor: "#FEF3C7",
borderColor: "#FDE68A",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 8,
},
eventSummaryBadgeText: {
color: "#92400E",
fontWeight: "900",
fontSize: 12,
},
eventEmptyBox: {
flex: 1,
borderRadius: 16,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#FFFFFF",
alignItems: "center",
justifyContent: "center",
padding: 16,
},
eventEmptyText: {
fontSize: 15,
fontWeight: "800",
color: "#6B7280",
textAlign: "center",
},
emptyState: {
flex: 1,
alignItems: "center",
justifyContent: "center",
},
emptyText: {
marginTop: 10,
color: "#6B7280",
fontSize: 18,
fontWeight: "700",
},
innerScroll: {
flex: 1,
},
cleaningGrid: {
flexDirection: "row",
flexWrap: "wrap",
gap: 10,
paddingBottom: 8,
},
cleaningCard: {
width: "31.8%",
minHeight: 86,
borderRadius: 16,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#F9FAFB",
padding: 12,
},
cleaningTask: {
fontSize: 15,
fontWeight: "900",
color: "#111827",
},
cleaningAssignedPill: {
alignSelf: "flex-start",
marginTop: 8,
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 11,
paddingVertical: 5,
maxWidth: "100%",
},
cleaningAssignedText: {
fontSize: 16,
fontWeight: "900",
},
cleaningAssigned: {
marginTop: 8,
fontSize: 18,
fontWeight: "900",
color: "#F54FA5",
},
cleaningUnassigned: {
marginTop: 8,
fontSize: 15,
fontWeight: "700",
color: "#9CA3AF",
},
progressBlock: {
alignItems: "flex-end",
},
progressText: {
fontSize: 16,
fontWeight: "900",
color: "#111827",
},
finalStaffLeftBlock: {
marginTop: 12,
alignItems: "flex-start",
},
finalStaffLabel: {
fontSize: 13,
fontWeight: "900",
color: "#374151",
textTransform: "uppercase",
letterSpacing: 0.5,
marginBottom: 6,
},
finalStaffPill: {
borderWidth: 1,
borderColor: "#F54FA5",
backgroundColor: "#FDF2FB",
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 7,
},
finalStaffPillText: {
color: "#F54FA5",
fontSize: 18,
fontWeight: "900",
},
checklistProgressOuter: {
height: 16,
borderRadius: 999,
backgroundColor: "#E5E7EB",
overflow: "hidden",
marginBottom: 16,
},
checklistProgressInner: {
height: "100%",
backgroundColor: "#10B981",
},
checklistList: {
gap: 9,
paddingBottom: 8,
},
checklistRow: {
minHeight: 50,
borderRadius: 14,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#F9FAFB",
paddingHorizontal: 12,
flexDirection: "row",
alignItems: "center",
gap: 12,
},
checklistRowDone: {
backgroundColor: "#ECFDF3",
borderColor: "#A7F3D0",
},
checklistText: {
fontSize: 17,
fontWeight: "800",
color: "#111827",
},
checklistTextDone: {
color: "#065F46",
},
reminderPanel: {
padding: 16,
},
reminderHeaderRow: {
flexDirection: "row",
alignItems: "center",
gap: 12,
marginBottom: 10,
},
reminderLogo: {
width: 62,
height: 62,
borderRadius: 999,
},
reminderHeaderText: {
flex: 1,
},
reminderIconCircle: {
width: 54,
height: 54,
borderRadius: 999,
backgroundColor: "#FDF2FB",
borderWidth: 1,
borderColor: "#F9A8D4",
alignItems: "center",
justifyContent: "center",
},
reminderBody: {
gap: 9,
paddingBottom: 2,
},
reminderLeadBox: {
borderRadius: 16,
backgroundColor: "#FDF2FB",
borderWidth: 1,
borderColor: "#F9A8D4",
paddingHorizontal: 14,
paddingVertical: 10,
},
reminderLeadText: {
fontSize: 18,
lineHeight: 24,
fontWeight: "900",
color: "#111827",
},
reminderPointList: {
gap: 7,
},
reminderPointRow: {
minHeight: 46,
borderRadius: 14,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#FFFFFF",
paddingHorizontal: 12,
flexDirection: "row",
alignItems: "center",
gap: 12,
},
reminderBullet: {
width: 26,
height: 26,
borderRadius: 999,
backgroundColor: "#F54FA5",
alignItems: "center",
justifyContent: "center",
},
reminderPointText: {
flex: 1,
fontSize: 16,
lineHeight: 21,
fontWeight: "800",
color: "#111827",
},
reminderFooterBanner: {
marginTop: 2,
borderRadius: 16,
backgroundColor: "#FCE7F3",
borderWidth: 1,
borderColor: "#F9A8D4",
paddingHorizontal: 14,
paddingVertical: 10,
flexDirection: "row",
alignItems: "center",
gap: 10,
},
reminderFooterText: {
flex: 1,
fontSize: 16,
lineHeight: 21,
fontWeight: "900",
color: "#BE185D",
},

celebrationPanel: {
position: "relative",
overflow: "hidden",
},
celebrationLightWatermark: {
position: "absolute",
top: 10,
right: 10,
width: 360,
height: 120,
borderRadius: 18,
opacity: 0.08,
},
celebrationSummaryBadge: {
flexDirection: "row",
alignItems: "center",
gap: 8,
backgroundColor: "#F3E8FF",
borderColor: "#DDD6FE",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 8,
},
celebrationSummaryBadgeText: {
color: "#6D28D9",
fontWeight: "900",
fontSize: 12,
},
celebrationLayout: {
flex: 1,
flexDirection: "row",
gap: 14,
marginTop: 8,
},
celebrationMainColumn: {
flex: 2.2,
},
celebrationSideColumn: {
flex: 1,
borderRadius: 18,
borderWidth: 1,
borderColor: "#E9D5FF",
backgroundColor: "#FFFFFF",
overflow: "hidden",
},
celebrationSectionTitleRow: {
flexDirection: "row",
alignItems: "center",
gap: 9,
marginBottom: 10,
},
celebrationSectionTitle: {
fontSize: 18,
fontWeight: "900",
color: "#5B21B6",
},
celebrationTodayGrid: {
flexDirection: "row",
flexWrap: "wrap",
gap: 12,
paddingBottom: 6,
},
celebrationTodayCard: {
minHeight: 178,
borderRadius: 22,
borderWidth: 1.5,
padding: 14,
position: "relative",
overflow: "hidden",
},
celebrationBirthdayCard: {
backgroundColor: "#FBF3FF",
borderColor: "#DDD6FE",
},
celebrationMilestoneCard: {
backgroundColor: "#FFFAEB",
borderColor: "#FDE68A",
},
celebrationConfettiCorner: {
position: "absolute",
top: 12,
right: 12,
opacity: 0.45,
},
celebrationTodayCardInner: {
flex: 1,
flexDirection: "row",
alignItems: "center",
gap: 14,
},
celebrationPhoto: {
borderWidth: 3,
borderColor: "#FFFFFF",
backgroundColor: "#F3F4F6",
},
celebrationInitialsCircle: {
alignItems: "center",
justifyContent: "center",
borderWidth: 3,
borderColor: "#FFFFFF",
backgroundColor: "#EDE9FE",
},
celebrationInitialsText: {
fontSize: 24,
fontWeight: "900",
color: "#6D28D9",
},
celebrationTodayTextBlock: {
flex: 1,
minWidth: 0,
},
celebrationTypePill: {
alignSelf: "flex-start",
flexDirection: "row",
alignItems: "center",
gap: 5,
borderRadius: 999,
paddingHorizontal: 10,
paddingVertical: 5,
marginBottom: 8,
},
celebrationBirthdayPill: {
backgroundColor: "#EDE9FE",
},
celebrationMilestonePill: {
backgroundColor: "#FEF3C7",
},
celebrationTypeText: {
fontSize: 10,
fontWeight: "900",
textTransform: "uppercase",
},
celebrationBirthdayText: {
color: "#7C3AED",
},
celebrationMilestoneText: {
color: "#B7791F",
},
celebrationTodayTitle: {
fontSize: 24,
lineHeight: 29,
fontWeight: "900",
},
celebrationBirthdayTitle: {
color: "#7C3AED",
},
celebrationMilestoneTitle: {
color: "#B7791F",
},
celebrationTodayMessage: {
marginTop: 8,
fontSize: 16,
lineHeight: 22,
fontWeight: "700",
color: "#111827",
},
celebrationYearsMedal: {
width: 72,
height: 72,
borderRadius: 999,
backgroundColor: "#FDE68A",
borderWidth: 2,
borderColor: "#FBBF24",
alignItems: "center",
justifyContent: "center",
},
celebrationYearsNumber: {
fontSize: 30,
lineHeight: 34,
fontWeight: "900",
color: "#92400E",
},
celebrationYearsLabel: {
fontSize: 9,
fontWeight: "900",
color: "#92400E",
},
celebrationFooterBanner: {
marginTop: 12,
borderRadius: 16,
backgroundColor: "#F3E8FF",
borderWidth: 1,
borderColor: "#E9D5FF",
paddingHorizontal: 18,
paddingVertical: 12,
flexDirection: "row",
alignItems: "center",
gap: 12,
},
celebrationFooterText: {
flex: 1,
fontSize: 17,
fontWeight: "900",
color: "#3B0764",
textAlign: "center",
},
celebrationEmptyTodayBox: {
flex: 1,
borderRadius: 22,
borderWidth: 1.5,
borderColor: "#DDD6FE",
backgroundColor: "#FFFFFF",
alignItems: "center",
justifyContent: "center",
padding: 18,
},
celebrationEmptyTitle: {
marginTop: 10,
fontSize: 20,
fontWeight: "900",
color: "#111827",
},
celebrationEmptyText: {
marginTop: 6,
fontSize: 14,
fontWeight: "700",
color: "#6B7280",
textAlign: "center",
},
celebrationUpcomingHeader: {
height: 54,
flexDirection: "row",
alignItems: "center",
gap: 8,
paddingHorizontal: 14,
borderBottomWidth: 1,
borderBottomColor: "#E9D5FF",
backgroundColor: "#FCF7FF",
},
celebrationUpcomingTitle: {
fontSize: 18,
fontWeight: "900",
color: "#5B21B6",
},
celebrationUpcomingList: {
paddingHorizontal: 14,
paddingVertical: 10,
},
celebrationUpcomingRow: {
minHeight: 70,
flexDirection: "row",
alignItems: "center",
gap: 10,
borderBottomWidth: 1,
borderBottomColor: "#F3E8FF",
paddingVertical: 9,
},
celebrationUpcomingTextBlock: {
flex: 1,
minWidth: 0,
},
celebrationUpcomingName: {
fontSize: 16,
fontWeight: "900",
color: "#111827",
},
celebrationUpcomingLabel: {
marginTop: 3,
fontSize: 13,
fontWeight: "800",
},
celebrationUpcomingDate: {
fontSize: 13,
fontWeight: "900",
color: "#6D28D9",
},
celebrationUpcomingEmpty: {
flex: 1,
alignItems: "center",
justifyContent: "center",
padding: 18,
},
});
