import { Platform, StyleSheet } from "react-native";
import { MAX_WIDTH } from "./dashboardTheme";

export const styles = StyleSheet.create({
screen: {
flex: 1,
backgroundColor: "#111827",
alignItems: "center",
justifyContent: "center",
},
screenTv: {
position: "fixed" as any,
top: 0,
right: 0,
bottom: 0,
left: 0,
width: "100vw" as any,
height: "100vh" as any,
alignItems: "stretch",
justifyContent: "flex-start",
backgroundColor: "#F8FAFC",
zIndex: 9999,
},
screenTvPreview: {
position: "fixed" as any,
top: 0,
right: 0,
bottom: 0,
left: 0,
width: "100vw" as any,
height: "100vh" as any,
backgroundColor: "#111827",
alignItems: "center",
justifyContent: "center",
overflow: "hidden",
zIndex: 9999,
},
tvCanvasViewport: {
overflow: "hidden",
backgroundColor: "#F8FAFC",
shadowColor: "#000",
shadowOpacity: 0.18,
shadowRadius: 18,
shadowOffset: { width: 0, height: 8 },
},
tvCanvasSurface: {
position: "absolute" as any,
top: 0,
left: 0,
transformOrigin: "top left" as any,
backgroundColor: "#F8FAFC",
overflow: "hidden",
},
appFrame: {
width: "100%",
maxWidth: MAX_WIDTH,
height: Platform.OS === "web" ? 780 : "100%",
backgroundColor: "#F8FAFC",
borderRadius: Platform.OS === "web" ? 22 : 0,
overflow: "hidden",
},
appFrameTv: {
width: "100%",
maxWidth: "none" as any,
height: "100%",
borderRadius: 12,
shadowOpacity: 0,
backgroundColor: "#F8FAFC",
// Built-in safe inset. This is intentionally inside the 16:9 canvas so the
// preview on an iMac matches the TV composition.
paddingHorizontal: 20,
paddingTop: 14,
paddingBottom: 14,
},
topBar: {
height: 112,
paddingHorizontal: 26,
paddingVertical: 14,
backgroundColor: "#F54FA5",
flexDirection: "row",
justifyContent: "space-between",
alignItems: "center",
},
topBarTv: {
height: 88,
paddingHorizontal: 30,
paddingVertical: 8,
alignItems: "center",
borderTopLeftRadius: 10,
borderTopRightRadius: 10,
},
topLeftBlock: {
flex: 1,
paddingRight: 18,
},
locationText: {
color: "#FFFFFF",
fontSize: 22,
lineHeight: 27,
fontWeight: "900",
},
locationTextTv: {
fontSize: 18,
lineHeight: 22,
},
programText: {
marginTop: 2,
color: "#FFE4F4",
fontSize: 13,
lineHeight: 17,
fontWeight: "800",
},
programTextTv: {
fontSize: 11,
lineHeight: 14,
},
dateText: {
marginTop: 1,
color: "#FFE4F4",
fontSize: 12,
lineHeight: 16,
fontWeight: "800",
},
dateTextTv: {
fontSize: 10,
lineHeight: 13,
},
phaseText: {
marginTop: 3,
color: "#FFFFFF",
fontSize: 11,
lineHeight: 14,
fontWeight: "900",
},
phaseTextTv: {
fontSize: 10,
lineHeight: 13,
},
previewClockText: {
marginTop: 2,
color: "#FFF7ED",
fontSize: 11,
lineHeight: 14,
fontWeight: "900",
textAlign: "right",
},
previewClockTextTv: {
fontSize: 10,
lineHeight: 12,
},
cycleText: {
marginTop: 0,
color: "#FFE4F4",
fontSize: 9,
lineHeight: 11,
fontWeight: "700",
},
cycleTextTv: {
marginTop: 1,
color: "#FFE4F4",
fontSize: 9,
lineHeight: 11,
fontWeight: "800",
textAlign: "right",
},
cycleInlineTextTv: {
marginTop: 2,
color: "#FFE4F4",
fontSize: 13,
lineHeight: 16,
fontWeight: "900",
textAlign: "right",
},
voiceToggle: {
marginTop: 7,
paddingHorizontal: 11,
paddingVertical: 6,
borderRadius: 999,
borderWidth: 1,
borderColor: "rgba(255,255,255,0.72)",
backgroundColor: "rgba(255,255,255,0.14)",
},
voiceToggleEnabled: {
backgroundColor: "rgba(255,255,255,0.28)",
},
voiceToggleText: {
color: "#FFFFFF",
fontSize: 11,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.5,
},

voiceToggleBar: {
paddingHorizontal: 9,
paddingVertical: 4,
borderRadius: 999,
borderWidth: 1,
borderColor: "#D1D5DB",
backgroundColor: "#F9FAFB",
},
voiceToggleBarEnabled: {
backgroundColor: "#DCFCE7",
borderColor: "#86EFAC",
},
voiceToggleBarText: {
color: "#374151",
fontSize: 9,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.45,
},
clockBlock: {
alignItems: "flex-end",
justifyContent: "center",
},
clockText: {
color: "#FFFFFF",
fontSize: 22,
lineHeight: 25,
fontWeight: "900",
},
clockTextTv: {
fontSize: 30,
lineHeight: 34,
},
currentPanelBar: {
height: 48,
backgroundColor: "#FFFFFF",
borderBottomWidth: 1,
borderBottomColor: "#E5E7EB",
paddingHorizontal: 24,
flexDirection: "row",
alignItems: "center",
justifyContent: "space-between",
},
currentPanelLeft: {
flexDirection: "row",
alignItems: "center",
gap: 10,
flexShrink: 1,
},
currentPanelBarTv: {
height: 34,
paddingHorizontal: 30,
},
currentPanelPill: {
paddingHorizontal: 16,
paddingVertical: 6,
borderRadius: 999,
backgroundColor: "#111827",
},
currentPanelLabel: {
fontSize: 12,
fontWeight: "800",
color: "#FFFFFF",
},
currentPanelLabelTv: {
fontSize: 10,
},
currentPanelValue: {
fontWeight: "900",
color: "#FFFFFF",
},
currentPanelCount: {
fontSize: 11,
fontWeight: "800",
color: "#6B7280",
},
currentPanelCountTv: {
fontSize: 10,
},
panelControlsRow: {
flexDirection: "row",
alignItems: "center",
gap: 10,
},
manualNavControls: {
flexDirection: "row",
alignItems: "center",
gap: 6,
},
manualNavControlsTv: {
gap: 4,
},
manualNavButton: {
width: 30,
height: 28,
borderRadius: 999,
borderWidth: 1,
borderColor: "#D1D5DB",
backgroundColor: "#F9FAFB",
alignItems: "center",
justifyContent: "center",
},
manualNavButtonText: {
fontSize: 18,
lineHeight: 20,
fontWeight: "900",
color: "#374151",
},
manualFullscreenButton: {
width: 30,
height: 28,
borderRadius: 999,
borderWidth: 1,
borderColor: "#D1D5DB",
backgroundColor: "#F9FAFB",
alignItems: "center",
justifyContent: "center",
},
manualFullscreenButtonExit: {
backgroundColor: "#FEF2F2",
borderColor: "#FCA5A5",
},
manualAutoButton: {
height: 28,
paddingHorizontal: 12,
borderRadius: 999,
borderWidth: 1,
borderColor: "#D1D5DB",
backgroundColor: "#FEF2F2",
alignItems: "center",
justifyContent: "center",
},
manualAutoButtonEnabled: {
backgroundColor: "#ECFDF5",
borderColor: "#86EFAC",
},
manualAutoButtonText: {
fontSize: 10,
lineHeight: 12,
fontWeight: "900",
color: "#374151",
textTransform: "uppercase",
letterSpacing: 0.45,
},
contentArea: {
flex: 1,
padding: 16,
},
contentAreaTv: {
paddingHorizontal: 16,
paddingTop: 10,
paddingBottom: 10,
},
panel: {
flex: 1,
backgroundColor: "#FFFFFF",
borderRadius: 18,
paddingHorizontal: 14,
paddingTop: 12,
paddingBottom: 12,
overflow: "hidden",
shadowColor: "#000",
shadowOpacity: 0.04,
shadowRadius: 8,
shadowOffset: { width: 0, height: 3 },
},
floatingPanel: {
// Keep the panel at its natural content height. Using `flex: 0` also sets
// flexBasis to 0 on React Native Web, which collapses the entire table.
flexGrow: 0,
flexShrink: 0,
flexBasis: "auto" as any,
// Leave a small clean cushion below the final 2:00–2:30pm row.
paddingBottom: 12,
},
panelHeaderRow: {
flexDirection: "row",
justifyContent: "space-between",
alignItems: "flex-start",
gap: 16,
marginBottom: 10,
paddingHorizontal: 4,
paddingTop: 2,
},
panelEyebrow: {
color: "#6B7280",
fontSize: 10,
fontWeight: "800",
textTransform: "uppercase",
letterSpacing: 0.7,
},
panelTitle: {
marginTop: 0,
fontSize: 20,
lineHeight: 23,
fontWeight: "900",
color: "#111827",
},
badge: {
flexDirection: "row",
alignItems: "center",
gap: 6,
backgroundColor: "#DCFCE7",
borderColor: "#DDD6FE",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 9,
paddingVertical: 4,
},
badgeText: {
color: "#059669",
fontWeight: "800",
fontSize: 10,
},
legendRow: {
flexDirection: "row",
alignItems: "center",
gap: 8,
flexWrap: "wrap",
justifyContent: "flex-end",
marginRight: 2,
},
legendPill: {
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 12,
paddingVertical: 7,
},
legendBlue: {
backgroundColor: "#FFFFFF",
borderColor: "#D1D5DB",
},
legendOrange: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
legendPurple: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
legendRed: {
backgroundColor: "#FEF2F2",
borderColor: "#EF4444",
},
legendText: {
color: "#4B5563",
fontSize: 12,
fontWeight: "900",
},
legendTextOrange: {
color: "#C2410C",
fontSize: 12,
fontWeight: "900",
},
legendTextPurple: {
color: "#6D28D9",
fontSize: 12,
fontWeight: "900",
},
legendTextRed: {
color: "#B91C1C",
fontSize: 12,
fontWeight: "900",
},
compactDashboardTile: {
flexDirection: "row",
alignItems: "center",
},
compactDashboardStaffPill: {
borderRadius: 999,
borderWidth: 1.5,
paddingHorizontal: 8,
paddingVertical: 4,
maxWidth: "40%",
flexShrink: 1,
},
compactDashboardStaffName: {
fontSize: 14,
lineHeight: 17,
fontWeight: "900",
},
compactDashboardChevron: {
marginHorizontal: 4,
flexShrink: 0,
},
compactDashboardTileContent: {
flex: 1,
minWidth: 0,
justifyContent: "center",
},
assignmentGrid: {
flexDirection: "row",
flexWrap: "wrap",
justifyContent: "flex-start",
rowGap: 8 as any,
columnGap: "1.13%" as any,
paddingHorizontal: 4,
paddingTop: 2,
paddingBottom: 8,
},
assignmentCard: {
width: "24.15%",
minHeight: 58,
borderRadius: 14,
borderWidth: 1.5,
paddingHorizontal: 8,
paddingVertical: 7,
},
assignmentCardOnsite: {
backgroundColor: "#FFFFFF",
borderColor: "#E5E7EB",
},
assignmentCardOuting1: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
assignmentCardOuting2: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
assignmentCardOuting3: {
backgroundColor: "#FEF2F2",
borderColor: "#EF4444",
},
assignmentStaffPill: {
alignSelf: "flex-start",
borderRadius: 999,
borderWidth: 1.5,
paddingHorizontal: 11,
paddingVertical: 5,
maxWidth: "100%",
},
assignmentStaffPillOnsite: {
backgroundColor: "#F54FA5",
borderColor: "#F54FA5",
},
assignmentStaffPillOuting1: {
backgroundColor: "#FFEDD5",
borderColor: "#FB923C",
},
assignmentStaffPillOuting2: {
backgroundColor: "#EDE9FE",
borderColor: "#8B5CF6",
},
assignmentStaffName: {
fontSize: 18,
lineHeight: 22,
fontWeight: "900",
},
assignmentStaffNameOnsite: {
color: "#FFFFFF",
},
assignmentStaffNameOuting1: {
color: "#C2410C",
},
assignmentStaffNameOuting2: {
color: "#6D28D9",
},
assignmentParticipantList: {
flexDirection: "row",
flexWrap: "wrap",
alignItems: "center",
gap: 4,
},
assignmentParticipantChip: {
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 7,
paddingVertical: 3,
maxWidth: "100%",
},
assignmentParticipantChipOnsite: {
backgroundColor: "#6F82F6",
borderColor: "#5868E8",
},
assignmentParticipantChipOuting1: {
backgroundColor: "#FFEDD5",
borderColor: "#FB923C",
},
assignmentParticipantChipOuting2: {
backgroundColor: "#EDE9FE",
borderColor: "#8B5CF6",
},
assignmentParticipantChipOuting3: {
backgroundColor: "#FEE2E2",
borderColor: "#EF4444",
},
assignmentUnassignedChip: {
backgroundColor: "#F3F4F6",
borderColor: "#D1D5DB",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 7,
paddingVertical: 3,
maxWidth: "100%",
},
assignmentUnassignedText: {
color: "#6B7280",
fontSize: 10,
lineHeight: 13,
fontWeight: "800",
},
assignmentParticipantName: {
fontSize: 11,
lineHeight: 14,
fontWeight: "900",
},
assignmentParticipantNameOnsite: {
color: "#FFFFFF",
},
assignmentParticipantNameOuting1: {
color: "#C2410C",
},
assignmentParticipantNameOuting2: {
color: "#6D28D9",
},
assignmentParticipantNameOuting3: {
color: "#B91C1C",
},
floatingTable: {
flex: 1,
borderWidth: 1,
borderColor: "#E5E7EB",
borderRadius: 16,
overflow: "hidden",
marginTop: 2,
},
floatingTableCompact: {
// Keep the table at its natural row height. `flex: 0` becomes a zero
// flex-basis on React Native Web, which hides all table rows.
flexGrow: 0,
flexShrink: 0,
flexBasis: "auto" as any,
},
floatRow: {
flexDirection: "row",
minHeight: 29,
borderBottomWidth: 1,
borderBottomColor: "#E5E7EB",
},
floatHeaderRow: {
minHeight: 27,
backgroundColor: "#EEF2FF",
},
rowEven: {
backgroundColor: "#FFFFFF",
},
rowOdd: {
backgroundColor: "#F9FAFB",
},
currentFloatRow: {
backgroundColor: "#DCFCE7",
borderLeftWidth: 8,
borderLeftColor: "#10B981",
},
floatCell: {
flex: 1,
paddingHorizontal: 8,
paddingVertical: 3,
},
floatHeaderText: {
fontSize: 12,
color: "#111827",
fontWeight: "900",
},
floatTimeCell: {
flex: 1.05,
},
floatCellBox: {
flex: 1,
justifyContent: "center",
paddingHorizontal: 10,
borderRightWidth: 1,
borderRightColor: "#E5E7EB",
},
floatTimeCellBox: {
flex: 1.05,
},
floatTimeText: {
fontSize: 12,
fontWeight: "800",
color: "#111827",
},
floatNameText: {
fontSize: 13,
fontWeight: "800",
color: "#111827",
},
floatEmptyText: {
fontSize: 13,
fontWeight: "800",
color: "#9CA3AF",
},
fsoText: {
color: "#F54FA5",
fontWeight: "900",
},
currentText: {
color: "#065F46",
},
nowLabel: {
marginTop: 1,
fontSize: 9,
color: "#059669",
fontWeight: "900",
},
outingGrid: {
flex: 1,
flexDirection: "row",
gap: 16,
marginTop: 12,
// Reserve the lower overlay lane so the outing card border finishes cleanly
// above the progress bar rather than continuing behind it.
marginBottom: 44,
},
outingCard: {
flex: 1,
borderRadius: 22,
borderWidth: 2,
padding: 20,
},
outingCardOrange: {
backgroundColor: "#FFF7ED",
borderColor: "#FB923C",
},
outingCardPurple: {
backgroundColor: "#F5F3FF",
borderColor: "#8B5CF6",
},
outingCardRed: {
backgroundColor: "#FEF2F2",
borderColor: "#EF4444",
},
outingTitleRow: {
flexDirection: "row",
alignItems: "center",
gap: 14,
marginBottom: 8,
},
outingIcon: {
width: 52,
height: 52,
borderRadius: 999,
alignItems: "center",
justifyContent: "center",
},
outingIconOrange: {
backgroundColor: "#F97316",
},
outingIconPurple: {
backgroundColor: "#7C3AED",
},
outingIconRed: {
backgroundColor: "#DC2626",
},
outingLabel: {
fontSize: 13,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.7,
},
orangeText: {
color: "#C2410C",
},
purpleText: {
color: "#6D28D9",
},
redText: {
color: "#B91C1C",
},
outingName: {
fontSize: 28,
fontWeight: "900",
color: "#111827",
},
outingTime: {
fontSize: 16,
color: "#4B5563",
fontWeight: "800",
},
outingSection: {
marginTop: 14,
},
outingSectionTitle: {
fontSize: 13,
fontWeight: "900",
color: "#374151",
textTransform: "uppercase",
letterSpacing: 0.5,
marginBottom: 4,
},
outingSectionText: {
fontSize: 18,
lineHeight: 25,
fontWeight: "700",
color: "#111827",
},
eventsGrid: {
  flexDirection: "row",
  gap: 12,
  marginTop: 4,
  height: 300,
},
eventsColumn: {
flex: 1,
borderRadius: 18,
borderWidth: 1,
borderColor: "#F3E8FF",
backgroundColor: "#FFF7FD",
padding: 9,
},
eventsSectionTitle: {
fontSize: 13,
fontWeight: "900",
color: "#111827",
marginBottom: 7,
},
eventsSectionBody: {
flex: 1,
},
eventsList: {
flexDirection: "row",
flexWrap: "wrap",
alignContent: "flex-start",
justifyContent: "space-between",
rowGap: 8 as any,
columnGap: 0 as any,
},
eventCard: {
width: "49.25%",
minHeight: 116,
flexDirection: "row",
alignItems: "flex-start",
gap: 7,
borderRadius: 15,
borderWidth: 1.5,
paddingHorizontal: 8,
paddingVertical: 8,
},
eventIconWrap: {
position: "relative" as any,
width: 31,
height: 31,
marginTop: 1,
},
eventIconCircle: {
width: 31,
height: 31,
borderRadius: 16,
alignItems: "center",
justifyContent: "center",
},
eventNumberBadge: {
position: "absolute" as any,
top: -6,
left: -6,
minWidth: 18,
height: 18,
borderRadius: 9,
alignItems: "center",
justifyContent: "center",
borderWidth: 2,
borderColor: "#FFFFFF",
paddingHorizontal: 4,
},
eventNumberText: {
color: "#FFFFFF",
fontSize: 9,
lineHeight: 11,
fontWeight: "900",
textAlign: "center",
},
eventCardBody: {
flex: 1,
minWidth: 0,
},
eventCardHeader: {
flexDirection: "row",
alignItems: "flex-start",
gap: 5,
},
eventHeadingBlock: {
flex: 1,
minWidth: 0,
},
eventStatusLabel: {
fontSize: 8,
lineHeight: 10,
fontWeight: "900",
textTransform: "uppercase",
letterSpacing: 0.65,
},
eventSubtitle: {
marginTop: 2,
fontSize: 9,
lineHeight: 11,
fontWeight: "800",
},
eventTitle: {
marginTop: 1,
fontSize: 14,
lineHeight: 16,
fontWeight: "900",
color: "#111827",
},
eventCategoryPill: {
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 7,
paddingVertical: 3,
},
eventCategoryText: {
fontSize: 9,
lineHeight: 11,
fontWeight: "900",
},
eventTypeText: {
marginTop: 3,
fontSize: 10,
lineHeight: 12,
fontWeight: "900",
color: "#4B5563",
},
eventDetailText: {
marginTop: 1,
fontSize: 9,
lineHeight: 11,
fontWeight: "700",
color: "#374151",
},
eventNoteBox: {
marginTop: 4,
borderRadius: 9,
paddingHorizontal: 7,
paddingVertical: 4,
},
eventNoteText: {
fontSize: 10,
lineHeight: 12,
fontWeight: "800",
},
eventSummaryBadge: {
flexDirection: "row",
alignItems: "center",
gap: 8,
backgroundColor: "#FEF3C7",
borderColor: "#FDE68A",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 8,
},
eventSummaryBadgeText: {
color: "#92400E",
fontWeight: "900",
fontSize: 12,
},
eventsMoreBadge: {
alignSelf: "flex-end",
marginTop: 7,
borderRadius: 999,
borderWidth: 1,
borderColor: "#E9D5FF",
backgroundColor: "#FAF5FF",
paddingHorizontal: 10,
paddingVertical: 4,
},
eventsMoreBadgeText: {
fontSize: 9,
lineHeight: 11,
fontWeight: "900",
color: "#7E22CE",
},
eventEmptyBox: {
flex: 1,
borderRadius: 16,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#FFFFFF",
alignItems: "center",
justifyContent: "center",
padding: 16,
},
eventEmptyText: {
fontSize: 15,
fontWeight: "800",
color: "#6B7280",
textAlign: "center",
},
emptyState: {
flex: 1,
alignItems: "center",
justifyContent: "center",
},
emptyText: {
marginTop: 10,
color: "#6B7280",
fontSize: 18,
fontWeight: "700",
},
innerScroll: {
flex: 1,
},
cleaningGrid: {
flexDirection: "row",
flexWrap: "wrap",
justifyContent: "flex-start",
rowGap: 8 as any,
columnGap: "1.13%" as any,
paddingBottom: 8,
},
cleaningCard: {
width: "24.15%",
minHeight: 58,
borderRadius: 14,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#F9FAFB",
paddingHorizontal: 8,
paddingVertical: 7,
},
cleaningTask: {
fontSize: 12,
lineHeight: 15,
fontWeight: "900",
color: "#111827",
},
progressBlock: {
alignItems: "flex-end",
},
progressText: {
fontSize: 16,
fontWeight: "900",
color: "#111827",
},
finalStaffLeftBlock: {
marginTop: 6,
alignItems: "flex-start",
},
finalStaffLabel: {
fontSize: 11,
fontWeight: "900",
color: "#374151",
textTransform: "uppercase",
letterSpacing: 0.5,
marginBottom: 6,
},
finalStaffPill: {
borderWidth: 1,
borderColor: "#F54FA5",
backgroundColor: "#FDF2FB",
borderRadius: 999,
paddingHorizontal: 12,
paddingVertical: 5,
},
finalStaffPillText: {
color: "#F54FA5",
fontSize: 15,
fontWeight: "900",
},
checklistProgressOuter: {
height: 8,
borderRadius: 999,
backgroundColor: "#E5E7EB",
overflow: "hidden",
marginBottom: 8,
},
checklistProgressInner: {
height: "100%",
backgroundColor: "#10B981",
},
checklistList: {
gap: 5,
paddingBottom: 4,
},
checklistRow: {
minHeight: 38,
borderRadius: 16,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#F9FAFB",
paddingHorizontal: 14,
flexDirection: "row",
alignItems: "center",
gap: 10,
},
checklistRowDone: {
backgroundColor: "#ECFDF3",
borderColor: "#A7F3D0",
},
checklistText: {
fontSize: 14,
fontWeight: "800",
color: "#111827",
},
checklistTextDone: {
color: "#065F46",
},
reminderPanel: {
padding: 18,
},
reminderHeaderRow: {
flexDirection: "row",
alignItems: "center",
gap: 12,
marginBottom: 10,
},
reminderLogo: {
width: 62,
height: 62,
borderRadius: 999,
},
reminderHeaderText: {
flex: 1,
},
reminderIconCircle: {
width: 54,
height: 54,
borderRadius: 999,
backgroundColor: "#FDF2FB",
borderWidth: 1,
borderColor: "#F9A8D4",
alignItems: "center",
justifyContent: "center",
},
reminderBody: {
gap: 9,
paddingBottom: 2,
},
reminderLeadBox: {
borderRadius: 18,
backgroundColor: "#FDF2FB",
borderWidth: 1,
borderColor: "#F9A8D4",
paddingHorizontal: 16,
paddingVertical: 10,
},
reminderLeadText: {
fontSize: 18,
lineHeight: 24,
fontWeight: "900",
color: "#111827",
},
reminderPointList: {
gap: 7,
},
reminderPointRow: {
minHeight: 46,
borderRadius: 16,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "#FFFFFF",
paddingHorizontal: 14,
flexDirection: "row",
alignItems: "center",
gap: 10,
},
reminderBullet: {
width: 26,
height: 26,
borderRadius: 999,
backgroundColor: "#F54FA5",
alignItems: "center",
justifyContent: "center",
},
reminderPointText: {
flex: 1,
fontSize: 16,
lineHeight: 21,
fontWeight: "800",
color: "#111827",
},
reminderFooterBanner: {
marginTop: 2,
borderRadius: 16,
backgroundColor: "#FCE7F3",
borderWidth: 1,
borderColor: "#F9A8D4",
paddingHorizontal: 14,
paddingVertical: 10,
flexDirection: "row",
alignItems: "center",
gap: 10,
},
reminderFooterText: {
flex: 1,
fontSize: 16,
lineHeight: 21,
fontWeight: "900",
color: "#BE185D",
},

celebrationPanel: {
position: "relative",
overflow: "hidden",
},
celebrationLightWatermark: {
position: "absolute",
top: 10,
right: 10,
width: 360,
height: 120,
borderRadius: 18,
opacity: 0.08,
},
celebrationSummaryBadge: {
flexDirection: "row",
alignItems: "center",
gap: 8,
backgroundColor: "#F3E8FF",
borderColor: "#DDD6FE",
borderWidth: 1,
borderRadius: 999,
paddingHorizontal: 14,
paddingVertical: 8,
},
celebrationSummaryBadgeText: {
color: "#6D28D9",
fontWeight: "900",
fontSize: 12,
},
celebrationLayout: {
flex: 1,
flexDirection: "row",
gap: 14,
marginTop: 8,
},
celebrationMainColumn: {
flex: 2.2,
},
celebrationSideColumn: {
flex: 1,
borderRadius: 18,
borderWidth: 1,
borderColor: "#E9D5FF",
backgroundColor: "#FFFFFF",
overflow: "hidden",
},
celebrationSectionTitleRow: {
flexDirection: "row",
alignItems: "center",
gap: 9,
marginBottom: 10,
},
celebrationSectionTitle: {
fontSize: 18,
fontWeight: "900",
color: "#5B21B6",
},
celebrationTodayGrid: {
flexDirection: "row",
flexWrap: "wrap",
gap: 12,
paddingBottom: 6,
},
celebrationTodayCard: {
minHeight: 178,
borderRadius: 22,
borderWidth: 1.5,
padding: 14,
position: "relative",
overflow: "hidden",
},
celebrationBirthdayCard: {
backgroundColor: "#FBF3FF",
borderColor: "#DDD6FE",
},
celebrationMilestoneCard: {
backgroundColor: "#FFFAEB",
borderColor: "#FDE68A",
},
celebrationConfettiCorner: {
position: "absolute",
top: 12,
right: 12,
opacity: 0.45,
},
celebrationTodayCardInner: {
flex: 1,
flexDirection: "row",
alignItems: "center",
gap: 14,
},
celebrationPhoto: {
borderWidth: 3,
borderColor: "#FFFFFF",
backgroundColor: "#F3F4F6",
},
celebrationInitialsCircle: {
alignItems: "center",
justifyContent: "center",
borderWidth: 3,
borderColor: "#FFFFFF",
backgroundColor: "#EDE9FE",
},
celebrationInitialsText: {
fontSize: 24,
fontWeight: "900",
color: "#6D28D9",
},
celebrationTodayTextBlock: {
flex: 1,
minWidth: 0,
},
celebrationTypePill: {
alignSelf: "flex-start",
flexDirection: "row",
alignItems: "center",
gap: 5,
borderRadius: 999,
paddingHorizontal: 10,
paddingVertical: 5,
marginBottom: 8,
},
celebrationBirthdayPill: {
backgroundColor: "#EDE9FE",
},
celebrationMilestonePill: {
backgroundColor: "#FEF3C7",
},
celebrationTypeText: {
fontSize: 10,
fontWeight: "900",
textTransform: "uppercase",
},
celebrationBirthdayText: {
color: "#7C3AED",
},
celebrationMilestoneText: {
color: "#B7791F",
},
celebrationTodayTitle: {
fontSize: 24,
lineHeight: 29,
fontWeight: "900",
},
celebrationBirthdayTitle: {
color: "#7C3AED",
},
celebrationMilestoneTitle: {
color: "#B7791F",
},
celebrationTodayMessage: {
marginTop: 8,
fontSize: 16,
lineHeight: 22,
fontWeight: "700",
color: "#111827",
},
celebrationYearsMedal: {
width: 72,
height: 72,
borderRadius: 999,
backgroundColor: "#FDE68A",
borderWidth: 2,
borderColor: "#FBBF24",
alignItems: "center",
justifyContent: "center",
},
celebrationYearsNumber: {
fontSize: 30,
lineHeight: 34,
fontWeight: "900",
color: "#92400E",
},
celebrationYearsLabel: {
fontSize: 9,
fontWeight: "900",
color: "#92400E",
},
celebrationFooterBanner: {
marginTop: 12,
borderRadius: 16,
backgroundColor: "#F3E8FF",
borderWidth: 1,
borderColor: "#E9D5FF",
paddingHorizontal: 18,
paddingVertical: 12,
flexDirection: "row",
alignItems: "center",
gap: 12,
},
celebrationFooterText: {
flex: 1,
fontSize: 17,
fontWeight: "900",
color: "#3B0764",
textAlign: "center",
},
celebrationEmptyTodayBox: {
flex: 1,
borderRadius: 22,
borderWidth: 1.5,
borderColor: "#DDD6FE",
backgroundColor: "#FFFFFF",
alignItems: "center",
justifyContent: "center",
padding: 18,
},
celebrationEmptyTitle: {
marginTop: 10,
fontSize: 20,
fontWeight: "900",
color: "#111827",
},
celebrationEmptyText: {
marginTop: 6,
fontSize: 14,
fontWeight: "700",
color: "#6B7280",
textAlign: "center",
},
celebrationUpcomingHeader: {
height: 54,
flexDirection: "row",
alignItems: "center",
gap: 8,
paddingHorizontal: 14,
borderBottomWidth: 1,
borderBottomColor: "#E9D5FF",
backgroundColor: "#FCF7FF",
},
celebrationUpcomingTitle: {
fontSize: 18,
fontWeight: "900",
color: "#5B21B6",
},
celebrationUpcomingList: {
paddingHorizontal: 14,
paddingVertical: 10,
},
celebrationUpcomingRow: {
minHeight: 70,
flexDirection: "row",
alignItems: "center",
gap: 10,
borderBottomWidth: 1,
borderBottomColor: "#F3E8FF",
paddingVertical: 9,
},
celebrationUpcomingTextBlock: {
flex: 1,
minWidth: 0,
},
celebrationUpcomingName: {
fontSize: 16,
fontWeight: "900",
color: "#111827",
},
celebrationUpcomingLabel: {
marginTop: 3,
fontSize: 13,
fontWeight: "800",
},
celebrationUpcomingDate: {
fontSize: 13,
fontWeight: "900",
color: "#6D28D9",
},
celebrationUpcomingEmpty: {
flex: 1,
alignItems: "center",
justifyContent: "center",
padding: 18,
},

dailyPhasePillOverlay: {
position: "absolute" as any,
right: "5%",
bottom: 78,
zIndex: 55,
width: 225,
alignItems: "flex-end",
flexDirection: "column-reverse",
gap: 7,
},
dailyPhasePill: {
minHeight: 34,
maxWidth: 225,
flexDirection: "row",
alignItems: "center",
borderRadius: 999,
borderWidth: 1,
paddingHorizontal: 13,
paddingVertical: 7,
backgroundColor: "rgba(255,255,255,0.96)" as any,
shadowColor: "#000",
shadowOpacity: 0.12,
shadowRadius: 8,
shadowOffset: { width: 0, height: 4 },
},
dailyPhaseDot: {
width: 9,
height: 9,
borderRadius: 999,
marginRight: 9,
},
dailyPhaseText: {
fontSize: 13,
lineHeight: 17,
fontWeight: "900",
letterSpacing: 0.1,
},
dailyPhasePillMorning: {
backgroundColor: "rgba(255,247,237,0.97)" as any,
borderColor: "#FDBA74",
},
dailyPhaseDotMorning: { backgroundColor: "#F97316" },
dailyPhaseTextMorning: { color: "#9A3412" },
dailyPhasePillActive: {
backgroundColor: "rgba(236,253,245,0.97)" as any,
borderColor: "#6EE7B7",
},
dailyPhaseDotActive: { backgroundColor: "#10B981" },
dailyPhaseTextActive: { color: "#047857" },
dailyPhasePillOuting: {
backgroundColor: "rgba(255,247,237,0.97)" as any,
borderColor: "#FB923C",
},
dailyPhaseDotOuting: { backgroundColor: "#EA580C" },
dailyPhaseTextOuting: { color: "#C2410C" },
dailyPhasePillMeeting: {
backgroundColor: "rgba(245,243,255,0.97)" as any,
borderColor: "#C4B5FD",
},
dailyPhaseDotMeeting: { backgroundColor: "#7C3AED" },
dailyPhaseTextMeeting: { color: "#6D28D9" },
dailyPhasePillLunch: {
backgroundColor: "rgba(255,251,235,0.97)" as any,
borderColor: "#FCD34D",
},
dailyPhaseDotLunch: { backgroundColor: "#D97706" },
dailyPhaseTextLunch: { color: "#92400E" },
dailyPhasePillCleaning: {
backgroundColor: "rgba(236,254,255,0.97)" as any,
borderColor: "#67E8F9",
},
dailyPhaseDotCleaning: { backgroundColor: "#0891B2" },
dailyPhaseTextCleaning: { color: "#0E7490" },
dailyPhasePillLounge: {
backgroundColor: "rgba(238,242,255,0.97)" as any,
borderColor: "#A5B4FC",
},
dailyPhaseDotLounge: { backgroundColor: "#4F46E5" },
dailyPhaseTextLounge: { color: "#4338CA" },
dailyPhasePillDropoffs: {
backgroundColor: "rgba(239,246,255,0.97)" as any,
borderColor: "#93C5FD",
},
dailyPhaseDotDropoffs: { backgroundColor: "#2563EB" },
dailyPhaseTextDropoffs: { color: "#1D4ED8" },
dailyPhasePillComplete: {
backgroundColor: "rgba(240,253,244,0.97)" as any,
borderColor: "#86EFAC",
},
dailyPhaseDotComplete: { backgroundColor: "#16A34A" },
dailyPhaseTextComplete: { color: "#166534" },

dailyProgressOverlay: {
position: "absolute" as any,
left: "5%",
right: "5%",
bottom: 32,
zIndex: 48,
},
dailyProgressTrack: {
height: 28,
flexDirection: "row",
borderRadius: 999,
borderWidth: 1,
borderColor: "rgba(139,155,163,0.42)" as any,
backgroundColor: "#E8EEF0",
overflow: "hidden",
shadowColor: "#000",
shadowOpacity: 0.09,
shadowRadius: 7,
shadowOffset: { width: 0, height: 3 },
},
dailyProgressSegment: {
flex: 1,
position: "relative",
alignItems: "center",
justifyContent: "center",
backgroundColor: "#D7E0E3",
overflow: "hidden",
},
dailyProgressSegmentFirst: {
borderTopLeftRadius: 999,
borderBottomLeftRadius: 999,
},
dailyProgressSegmentLast: {
borderTopRightRadius: 999,
borderBottomRightRadius: 999,
},
dailyProgressSegmentDivider: {
borderLeftWidth: 1,
borderLeftColor: "rgba(255,255,255,0.72)" as any,
},
dailyProgressSegmentCompleted: {
backgroundColor: "#67B5AE",
},
dailyProgressSegmentCurrent: {
backgroundColor: "#267F8A",
},
dailyProgressCurrentFill: {
position: "absolute" as any,
left: 0,
top: 0,
bottom: 0,
backgroundColor: "rgba(154,221,215,0.34)" as any,
},
dailyProgressCurrentGlow: {
position: "absolute" as any,
left: 2,
right: 2,
top: 2,
bottom: 2,
borderRadius: 999,
borderWidth: 1,
borderColor: "#9ADDD7",
shadowColor: "#9ADDD7",
shadowOpacity: 0.65,
shadowRadius: 6,
shadowOffset: { width: 0, height: 0 },
},
dailyProgressIconWrap: {
zIndex: 2,
alignItems: "center",
justifyContent: "center",
},

floatingBannerOverlay: {
position: "absolute" as any,
left: "5%",
right: "32%",
bottom: 78,
zIndex: 40,
},
floatingBannerGlassPanel: {
borderRadius: 18,
borderWidth: 1,
borderColor: "rgba(148,163,184,0.28)" as any,
backgroundColor: "rgba(248,250,252,0.96)" as any,
paddingHorizontal: 10,
paddingVertical: 6,
shadowColor: "#000",
shadowOpacity: 0.08,
shadowRadius: 10,
shadowOffset: { width: 0, height: 5 },
gap: 4,
},
floatingBannerPanelTitle: {
fontSize: 14,
lineHeight: 16,
fontWeight: "900",
color: "#111827",
marginBottom: 0,
},
floatingBannerRow: {
minHeight: 42,
flexDirection: "row",
alignItems: "center",
borderRadius: 14,
borderWidth: 0,
paddingHorizontal: 4,
paddingVertical: 3,
overflow: "hidden",
},
floatingBannerRowCurrent: {
backgroundColor: "transparent",
borderColor: "transparent",
},
floatingBannerRowUpNext: {
backgroundColor: "transparent",
borderColor: "transparent",
},
floatingBannerRowLabelBlock: {
width: 118,
minHeight: 34,
borderRadius: 12,
paddingHorizontal: 8,
paddingVertical: 4,
justifyContent: "center",
marginRight: 7,
flexShrink: 0,
},
floatingBannerRowLabelBlockCurrent: {
backgroundColor: "rgba(220,252,231,0.38)" as any,
},
floatingBannerRowLabelBlockUpNext: {
backgroundColor: "rgba(255,237,213,0.38)" as any,
},
floatingBannerRowTitle: {
fontSize: 15,
lineHeight: 17,
fontWeight: "900",
},
floatingBannerRowTitleCurrent: {
color: "#047857",
},
floatingBannerRowTitleUpNext: {
color: "#C2410C",
},
floatingBannerRowSubtitle: {
marginTop: 1,
fontSize: 9,
lineHeight: 11,
fontWeight: "900",
color: "#374151",
},
floatingBannerAssignmentsGrid: {
flex: 1,
minWidth: 0,
flexDirection: "row",
alignItems: "center",
gap: 8,
},
floatingBannerStaffCard: {
flex: 1,
flexGrow: 1,
flexShrink: 1,
minWidth: 0,
minHeight: 34,
flexDirection: "row",
alignItems: "center",
gap: 7,
borderRadius: 12,
borderWidth: 1,
borderColor: "#E5E7EB",
backgroundColor: "rgba(255,255,255,0.9)" as any,
paddingHorizontal: 7,
paddingVertical: 3,
},
floatingBannerAvatarWrap: {
width: 30,
height: 30,
borderRadius: 999,
borderWidth: 0,
overflow: "hidden",
backgroundColor: "transparent",
flexShrink: 0,
},
floatingBannerAvatar: {
width: "100%",
height: "100%",
},
floatingBannerInitialsAvatar: {
width: "100%",
height: "100%",
alignItems: "center",
justifyContent: "center",
borderRadius: 999,
backgroundColor: "#FCE7F3",
},
floatingBannerInitialsText: {
fontSize: 11,
fontWeight: "900",
color: "#BE185D",
},
floatingBannerStaffTextBlock: {
flex: 1,
minWidth: 0,
},
floatingBannerStaffName: {
fontSize: 13,
lineHeight: 15,
fontWeight: "900",
color: "#111827",
},
floatingBannerRoomName: {
marginTop: 1,
fontSize: 9,
lineHeight: 11,
fontWeight: "900",
color: "#475569",
},

});
