import type { ImageSourcePropType } from "react-native";

export type StaffPhotoKey = "Anita" | "Antoinette" | "Antonia" | "Bruno" | "Charbel" | "Charlie" | "Chelsea" | "Claudette" | "Crystal" | "Dalida" | "Eliana" | "Gabriel" | "George" | "Gilda" | "Isabella" | "Jamie" | "Jessica" | "Juliet" | "Liana" | "Liya" | "Maray" | "Marianne" | "Mary" | "Merna" | "Michelle" | "Mikaela" | "Miraye" | "Natalie" | "Peter" | "Princess" | "Readium" | "Rebecca" | "Tayla" | "Tema" | "Theresia" | "Violet" | "William";

export const STAFF_PHOTO_ASSETS: Partial<Record<StaffPhotoKey, ImageSourcePropType>> = {
  "Anita": require("../../assets/images/staff/Anita.png"),
  "Antoinette": require("../../assets/images/staff/Antoinette.png"),
  "Antonia": require("../../assets/images/staff/Antonia.png"),
  "Bruno": require("../../assets/images/staff/Bruno.png"),
  "Charbel": require("../../assets/images/staff/Charbel.png"),
  "Charlie": require("../../assets/images/staff/Charlie.png"),
  "Chelsea": require("../../assets/images/staff/Chelsea.png"),
  "Claudette": require("../../assets/images/staff/Claudette.png"),
  "Crystal": require("../../assets/images/staff/Crystal.png"),
  "Dalida": require("../../assets/images/staff/Dalida.png"),
  "Eliana": require("../../assets/images/staff/Eliana.png"),
  "Gabriel": require("../../assets/images/staff/Gabriel.png"),
  "George": require("../../assets/images/staff/George.png"),
  "Gilda": require("../../assets/images/staff/Gilda.png"),
  "Isabella": require("../../assets/images/staff/Isabella.png"),
  "Jamie": require("../../assets/images/staff/Jamie.png"),
  "Jessica": require("../../assets/images/staff/Jessica.png"),
  "Juliet": require("../../assets/images/staff/Juliet.png"),
  "Liana": require("../../assets/images/staff/Liana.png"),
  "Liya": require("../../assets/images/staff/Liya.png"),
  "Maray": require("../../assets/images/staff/Maray.png"),
  "Marianne": require("../../assets/images/staff/Marianne.png"),
  "Mary": require("../../assets/images/staff/Mary.png"),
  "Merna": require("../../assets/images/staff/Merna.png"),
  "Michelle": require("../../assets/images/staff/Michelle.png"),
  "Mikaela": require("../../assets/images/staff/Mikaela.png"),
  "Miraye": require("../../assets/images/staff/Miraye.png"),
  "Natalie": require("../../assets/images/staff/Natalie.png"),
  "Peter": require("../../assets/images/staff/Peter.png"),
  "Princess": require("../../assets/images/staff/Princess.png"),
  "Readium": require("../../assets/images/staff/Readium.png"),
  "Rebecca": require("../../assets/images/staff/Rebecca.png"),
  "Tayla": require("../../assets/images/staff/Tayla.png"),
  "Tema": require("../../assets/images/staff/Tema.png"),
  "Theresia": require("../../assets/images/staff/Theresia.png"),
  "Violet": require("../../assets/images/staff/Violet.png"),
  "William": require("../../assets/images/staff/William.png"),
};
