/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/help`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/share-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/edit/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/edit/checklist`; params?: Router.UnknownInputParams; } | { pathname: `/edit/cleaning`; params?: Router.UnknownInputParams; } | { pathname: `/edit/dream-team`; params?: Router.UnknownInputParams; } | { pathname: `/edit/floating`; params?: Router.UnknownInputParams; } | { pathname: `/edit`; params?: Router.UnknownInputParams; } | { pathname: `/edit/participants`; params?: Router.UnknownInputParams; } | { pathname: `/edit/pickups-dropoffs`; params?: Router.UnknownInputParams; } | { pathname: `/api/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create-schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/help`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/share-schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/assignments`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/checklist`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/cleaning`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/dream-team`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/floating`; params?: Router.UnknownOutputParams; } | { pathname: `/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/participants`; params?: Router.UnknownOutputParams; } | { pathname: `/edit/pickups-dropoffs`; params?: Router.UnknownOutputParams; } | { pathname: `/api/[code]`, params: Router.UnknownOutputParams & { code: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/create-schedule${`?${string}` | `#${string}` | ''}` | `/help${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/share-schedule${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/edit/assignments${`?${string}` | `#${string}` | ''}` | `/edit/checklist${`?${string}` | `#${string}` | ''}` | `/edit/cleaning${`?${string}` | `#${string}` | ''}` | `/edit/dream-team${`?${string}` | `#${string}` | ''}` | `/edit/floating${`?${string}` | `#${string}` | ''}` | `/edit${`?${string}` | `#${string}` | ''}` | `/edit/participants${`?${string}` | `#${string}` | ''}` | `/edit/pickups-dropoffs${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/help`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/share-schedule`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/edit/assignments`; params?: Router.UnknownInputParams; } | { pathname: `/edit/checklist`; params?: Router.UnknownInputParams; } | { pathname: `/edit/cleaning`; params?: Router.UnknownInputParams; } | { pathname: `/edit/dream-team`; params?: Router.UnknownInputParams; } | { pathname: `/edit/floating`; params?: Router.UnknownInputParams; } | { pathname: `/edit`; params?: Router.UnknownInputParams; } | { pathname: `/edit/participants`; params?: Router.UnknownInputParams; } | { pathname: `/edit/pickups-dropoffs`; params?: Router.UnknownInputParams; } | `/api/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/api/[code]`, params: Router.UnknownInputParams & { code: string | number; } };
    }
  }
}
